In [80]:
import pandas as pd
from sqlalchemy import create_engine

In [81]:
df = pd.read_csv("g11_Delivery_warehouses.csv", sep = ';', parse_dates=['order_date','created_date'], dayfirst=True)

In [82]:
df_company = df.loc[:,['company_id','name','created_date']]

In [83]:
df_company = df_company.drop_duplicates(subset='company_id', keep='first')

In [84]:
df.head(3)

,company_id,warehouse_id,order_date,cost,name,created_date,designation,type,vehicle_id,comments
0,103,58,2023-08-01,4797,Bridges-Christensen,2022-10-29,New York,Automated Warehouse,NaN,NaN
1,246,436,2024-10-09,1585,Miller-Ford,2023-06-29,Los Angeles,Cold Storage Center,NaN,NaN
2,66,20,2023-10-29,1010,Doyle-Sosa,2023-09-29,Chicago,Climate-Controlled Distribution Hub,NaN,NaN

In [85]:
df[df['company_id']==55]

,company_id,warehouse_id,order_date,cost,name,created_date,designation,type,vehicle_id,comments
406,55,671,2023-11-12,4723,Chang-Johnson,2021-03-08,North Buffalo Valley,Spare-Parts Distribution Facility,NaN,NaN
480,55,938,2023-11-11,677,Chang-Johnson,2021-03-08,North Grand Prairie Grove,High-Bay Distribution Hub 273,NaN,NaN
1163,55,391,2021-10-18,2010,Chang-Johnson,2021-03-08,South Orlando Heights,Seasonal Inventory Depot 456,NaN,NaN
1515,55,525,2022-04-08,280,Chang-Johnson,2021-03-08,Pomona,Hazardous Warehouse 391,NaN,NaN
1695,55,762,2021-08-20,2769,Chang-Johnson,2021-03-08,North Madison Heights,Import Material Storage 236,NaN,NaN
2912,55,924,2023-11-23,3289,Chang-Johnson,2021-03-08,Grand Rapids,Regional Cargo Facility 340,NaN,NaN
4334,55,379,2021-04-07,4372,Chang-Johnson,2021-03-08,North Fort Wayne Creek,Bonded Distribution Hub 528,NaN,NaN
4645,55,525,2022-04-19,1497,Chang-Johnson,2021-03-08,Pomona,Hazardous Warehouse 391,NaN,NaN
5495,55,930,2021-12-04,1415,Chang-Johnson,2021-03-08,South Corpus Christi Harbor,AI-Managed Supply Warehouse,NaN,NaN
5630,55,241,2022-01-05,3801,Chang-Johnson,2021-03-08,North Reno Ridge,Transit Warehouse 271,NaN,NaN
6138,55,416,2021-04-07,2627,Chang-Johnson,2021-03-08,Los Angeles,Climate-Controlled Goods Repository,NaN,NaN
6879,55,510,2023-10-29,3826,Chang-Johnson,2021-03-08,Huntington Beach,Equipment Material Storage,NaN,NaN
7496,55,407,2023-10-31,2533,Chang-Johnson,2021-03-08,North Rochester Park,Regional Cargo Facility 550,NaN,NaN
9036,55,713,2022-03-06,2137,Chang-Johnson,2021-03-08,Waco,Export Distribution Facility,NaN,NaN
9366,55,619,2025-08-11,3379,Chang-Johnson,2021-03-08,Austin,Smart Material Storage,NaN,NaN

In [86]:
df_company.head(3)

   company_id                 name created_date
0         103  Bridges-Christensen   2022-10-29
1         246          Miller-Ford   2023-06-29
2          66           Doyle-Sosa   2023-09-29

In [87]:
len(df_company)

500

In [88]:
df_company = df_company.drop_duplicates(subset='company_id', keep='first')

In [89]:
len(df_company)

500

In [90]:
df_company.rename(columns={'company':'id'}, inplace=True)

In [91]:
df_company.insert(0, 'company', range(1, len(df_company) + 1))

In [92]:
import pandas as pd

In [93]:
engine = create_engine('sqlite:///DATABASEFINAL.db')

In [94]:
df_company.to_sql('company', con=engine, if_exists='append', index=False)

500

In [95]:
result = pd.read_sql('company', con=engine)

In [96]:
result.head(3)

   company  company_id                 name created_date
0        1         103  Bridges-Christensen   2022-10-29
1        2         246          Miller-Ford   2023-06-29
2        3          66           Doyle-Sosa   2023-09-29

In [97]:
df_company.to_csv('company.csv', sep=';',index = False)

In [98]:
engine.dispose()